version: "3.8"

services:
  db:
    image: postgres:15
    container_name: amorz-db
    restart: always
    environment:
      POSTGRES_USER: amorz
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: amorzdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata-amorz:/var/lib/postgresql/data

volumes:
  pgdata-amorz:
